#!/system/bin/sh
############################################################
# Created By: TrevE @ xda
#
# This ugly hack symlinks bins around to switch tether apps 
###########################################################

busybox mount -o rw,remount /system;

if [ -e /system/bin/hostapd_4wifitether ]; then
	#remove symlinks
	busybox rm -f /system/bin/hostapd;
	
	#create new symlinks
	busybox ln -s /system/bin/hostapd_4wifitether /system/bin/hostapd;
fi;

busybox mount -o ro,remount /system;