/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_tether_system_NativeTask */

#ifndef _Included_android_tether_system_NativeTask
#define _Included_android_tether_system_NativeTask
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_tether_system_NativeTask
 * Method:    getProp
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_android_tether_system_NativeTask_getProp
  (JNIEnv *, jclass, jstring);

/*
 * Class:     android_tether_system_NativeTask
 * Method:    runRootCommand
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_android_tether_system_NativeTask_runRootCommand
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
