#!/system/bin/sh
############################################################
# Created By: TrevE @ xda
#
# This ugly hack symlinks bins around to switch tether apps 
###########################################################

busybox mount -o rw,remount /system;

if [ -e /system/bin/hostapd_4stocktether ]; then
	#remove wifitether bins
	busybox rm -f /system/bin/hostapd_4wifitether;
	
	#move stock tether bins
	busybox mv /system/bin/hostapd_4stocktether /system/bin/hostapd;
	
	#perms
	busybox chmod 755 /system/bin/hostapd
	busybox chown 0:2000 /system/bin/hostapd;	
fi;

#cleanup old install
if [ -e /system/bin/netd_4stocktether ]; then
	busybox rm -f /system/bin/ndc_4wifitether;
	busybox rm -f /system/bin/netd_4wifitether;
	busybox rm -f /system/bin/ndc;
	busybox rm -f /system/bin/netd;
	busybox mv /system/bin/ndc_4stocktether /system/bin/ndc;
	busybox mv /system/bin/netd_4stocktether /system/bin/netd;
	busybox chmod 755 /system/bin/ndc;
	busybox chmod 755 /system/bin/netd;
	busybox chown 0:2000 /system/bin/ndc;
	busybox chown 0:2000 /system/bin/netd;
fi;
	
busybox mount -o ro,remount /system;